require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DownloadsController do

  # This should return the minimal set of attributes required to create a valid
  # Download. As you add validations to Download, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DownloadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all downloads as @downloads" do
      download = Download.create! valid_attributes
      get :index, {}, valid_session
      assigns(:downloads).should eq([download])
    end
  end

  describe "GET show" do
    it "assigns the requested download as @download" do
      download = Download.create! valid_attributes
      get :show, {:id => download.to_param}, valid_session
      assigns(:download).should eq(download)
    end
  end

  describe "GET new" do
    it "assigns a new download as @download" do
      get :new, {}, valid_session
      assigns(:download).should be_a_new(Download)
    end
  end

  describe "GET edit" do
    it "assigns the requested download as @download" do
      download = Download.create! valid_attributes
      get :edit, {:id => download.to_param}, valid_session
      assigns(:download).should eq(download)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Download" do
        expect {
          post :create, {:download => valid_attributes}, valid_session
        }.to change(Download, :count).by(1)
      end

      it "assigns a newly created download as @download" do
        post :create, {:download => valid_attributes}, valid_session
        assigns(:download).should be_a(Download)
        assigns(:download).should be_persisted
      end

      it "redirects to the created download" do
        post :create, {:download => valid_attributes}, valid_session
        response.should redirect_to(Download.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved download as @download" do
        # Trigger the behavior that occurs when invalid params are submitted
        Download.any_instance.stub(:save).and_return(false)
        post :create, {:download => {  }}, valid_session
        assigns(:download).should be_a_new(Download)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Download.any_instance.stub(:save).and_return(false)
        post :create, {:download => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested download" do
        download = Download.create! valid_attributes
        # Assuming there are no other downloads in the database, this
        # specifies that the Download created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Download.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => download.to_param, :download => { "these" => "params" }}, valid_session
      end

      it "assigns the requested download as @download" do
        download = Download.create! valid_attributes
        put :update, {:id => download.to_param, :download => valid_attributes}, valid_session
        assigns(:download).should eq(download)
      end

      it "redirects to the download" do
        download = Download.create! valid_attributes
        put :update, {:id => download.to_param, :download => valid_attributes}, valid_session
        response.should redirect_to(download)
      end
    end

    describe "with invalid params" do
      it "assigns the download as @download" do
        download = Download.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Download.any_instance.stub(:save).and_return(false)
        put :update, {:id => download.to_param, :download => {  }}, valid_session
        assigns(:download).should eq(download)
      end

      it "re-renders the 'edit' template" do
        download = Download.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Download.any_instance.stub(:save).and_return(false)
        put :update, {:id => download.to_param, :download => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested download" do
      download = Download.create! valid_attributes
      expect {
        delete :destroy, {:id => download.to_param}, valid_session
      }.to change(Download, :count).by(-1)
    end

    it "redirects to the downloads list" do
      download = Download.create! valid_attributes
      delete :destroy, {:id => download.to_param}, valid_session
      response.should redirect_to(downloads_url)
    end
  end

end
