require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # QuestionGroup. As you add validations to QuestionGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestionGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all question_groups as @question_groups" do
      question_group = QuestionGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:question_groups).should eq([question_group])
    end
  end

  describe "GET show" do
    it "assigns the requested question_group as @question_group" do
      question_group = QuestionGroup.create! valid_attributes
      get :show, {:id => question_group.to_param}, valid_session
      assigns(:question_group).should eq(question_group)
    end
  end

  describe "GET new" do
    it "assigns a new question_group as @question_group" do
      get :new, {}, valid_session
      assigns(:question_group).should be_a_new(QuestionGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested question_group as @question_group" do
      question_group = QuestionGroup.create! valid_attributes
      get :edit, {:id => question_group.to_param}, valid_session
      assigns(:question_group).should eq(question_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionGroup" do
        expect {
          post :create, {:question_group => valid_attributes}, valid_session
        }.to change(QuestionGroup, :count).by(1)
      end

      it "assigns a newly created question_group as @question_group" do
        post :create, {:question_group => valid_attributes}, valid_session
        assigns(:question_group).should be_a(QuestionGroup)
        assigns(:question_group).should be_persisted
      end

      it "redirects to the created question_group" do
        post :create, {:question_group => valid_attributes}, valid_session
        response.should redirect_to(QuestionGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question_group as @question_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionGroup.any_instance.stub(:save).and_return(false)
        post :create, {:question_group => {}}, valid_session
        assigns(:question_group).should be_a_new(QuestionGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionGroup.any_instance.stub(:save).and_return(false)
        post :create, {:question_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question_group" do
        question_group = QuestionGroup.create! valid_attributes
        # Assuming there are no other question_groups in the database, this
        # specifies that the QuestionGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => question_group.to_param, :question_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested question_group as @question_group" do
        question_group = QuestionGroup.create! valid_attributes
        put :update, {:id => question_group.to_param, :question_group => valid_attributes}, valid_session
        assigns(:question_group).should eq(question_group)
      end

      it "redirects to the question_group" do
        question_group = QuestionGroup.create! valid_attributes
        put :update, {:id => question_group.to_param, :question_group => valid_attributes}, valid_session
        response.should redirect_to(question_group)
      end
    end

    describe "with invalid params" do
      it "assigns the question_group as @question_group" do
        question_group = QuestionGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_group.to_param, :question_group => {}}, valid_session
        assigns(:question_group).should eq(question_group)
      end

      it "re-renders the 'edit' template" do
        question_group = QuestionGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_group.to_param, :question_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question_group" do
      question_group = QuestionGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => question_group.to_param}, valid_session
      }.to change(QuestionGroup, :count).by(-1)
    end

    it "redirects to the question_groups list" do
      question_group = QuestionGroup.create! valid_attributes
      delete :destroy, {:id => question_group.to_param}, valid_session
      response.should redirect_to(question_groups_url)
    end
  end

end
